### ISSUE TITLE
Support for URL rewrite in Storefront

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#345]
As a Magento Developer, 

I would like GrraphQL to return product URL rewrite functionality in a highly performant and scalable way by building the feature in the Catalog Storefront app

So that

Merchants who install Catalog Storefront app can continue to show products on Storefront by different URLs.

<ins>**Acceptance Criteria**</ins>
* Catalog Storefront support the same URL rewrite functionality currently built into the monolith
* Cover changes with SF API test for URL rewrites and canonical url

Tech detail:

* \Magento\CatalogExtractor\DataProvider\UrlRewrites\UrlRewritesDataProvider should be moved and adapted for Export API
* Do mapping for canonical URL in \Magento\CatalogMessageBroker\Model\ProductDataProcessor::$map "url > canonical_url"
* Add to et_schema.xml structure which cover SF API:
```
  Product {
    ...
   repeated UrlRewrite url_rewrites = 82;
    ...
  }
  message UrlRewrite {
    string url = 1;
    repeated UrlRewriteParameter parameters = 2;
  }

```

* Remove Old Data Extractor and any related code
  * \Magento\CatalogExtractor\DataProvider\UrlRewrites\UrlRewritesDataProvider
  * \Magento\CatalogExtractor\DataProvider\CanonicalUrl\CanonicalUrlDataProvider
* Cover with SF API Test (see example \Magento\CatalogStorefront\Test\Api\Product\ProductOptions\ShopperInputOptionsTest)

**Comment by mslabko** [comment]
Please, re-create repo , merge latest changes and re-run tests

**Comment by owlsmage** [comment]
@mslabko i recreated PR from saas-export into commerce-data-export repo
https://github.com/magento/commerce-data-export/pull/6
