### ISSUE TITLE
GetVariantsMatch service

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#359]
Depends on https://github.com/magento/catalog-storefront/issues/357

### Steps

* implement **GetVariantsMatch* request for *VariantSearchService** in proto:

```
message OptionSelectionRequest
{
  string store = 1;
  repeated string values = 2;
}

message ProductVariantResponse {
  repeated ProductVariant matched_variants = 3;
}

service VariantService {
  rpc GetVariantsMatch (OptionSelectionRequest) returns (ProductVariantResponse);
}
```
* see  https://github.com/magento/catalog-storefront/blob/develop/dev/docs/designDocuments/Configurable-products-option-variants.md for general details
* see https://github.com/magento/catalog-storefront/blob/develop/dev/docs/designDocuments/Product-Variants-services.md for details about services
* cover with API-functional tests

**Comment by bricht** [comment]
@magento I am working on this
