### ISSUE TITLE
Message Broker standalone installation

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#398]
The goal of this story is to install and run a Message Broker as a standalone application without Magento modules

AC:
* consumers successfully run without the necessity to install any of Magento module 
* new service added to docker-compose which handle only Catalog Message Broker application
  * services added and working in https://github.com/duhon/magento-docker/blob/storefront/bundles/grpc.yml

Tech details:
* ideally, application should not require DB connection, possible some overrides of Frmaewok parts is required
* possible Magento Framework part responsilbe for run `bin/magento queue:consumer:start <consumer name>` will require some information in etc/config.php, etc/env.php files - only minimum amount of information should be provided
* list of consumers: see app/code/Magento/CatalogMessageBroker/etc/queue_consumer.xml

**Comment by skovalenk** [comment]
PR: https://github.com/magento/storefront-message-broker/pull/1

**Comment by skovalenk** [comment]
PR: https://github.com/magento/storefront-message-broker/pull/1
