### ISSUE TITLE
[357.6] GetVariantsMatch service

### ISSUE THREAD

**Issue by bricht** [magento/catalog-storefront#414]
Subtask of https://github.com/magento/catalog-storefront/issues/357

Depends on https://github.com/magento/catalog-storefront/issues/331

Steps
   Implement GetVariantsMatch service.

message OptionSelectionRequest
{
  string store = 1;
  // array of option_values with the following format parent_id:option_id/optionValue.uid
  // @see ProductValue.option_values
  repeated string values = 2;
}

```
service VariantService {
  rpc GetVariantsMatch (OptionSelectionRequest) returns (ProductVariantResponse) {}
}
```

see https://github.com/magento/catalog-storefront/blob/develop/dev/docs/designDocuments/Configurable-products-option-variants.md for technical details.
    cover with API-functional tests

**Comment by RuslanKostiv1** [comment]
@bricht , we already have an issue for `GetVariantsMatch` 
https://github.com/magento/catalog-storefront/issues/359 , this one can be closed as duplicate
