### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by lenaorobei** [magento/catalog-storefront#424]
![306_Slack_logo-512](https://user-images.githubusercontent.com/17548019/98713680-8376ff80-234d-11eb-8a06-023189b24fd3.png)
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. Attachment
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by lenaorobei** [comment]
@magento export issue to Jira project SFAPP as bug

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/catalog-storefront is not supported in JIRA project SFAPP and type bug.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/catalog-storefront is not supported in JIRA project SFAPP and type bug.

**Comment by lenaorobei** [comment]
@magento export issue to Jira project SFAPP

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/catalog-storefront is not supported in JIRA project SFAPP and type bug.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-135) is successfully created for this issue.
