### ISSUE TITLE
Configuration propagation

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#427]
Store configuration settings which can modify Storefront should be propagated to Storefront

AC:
* Create a new event which will send a message with Configuration data to Message Broker from Export API
  * collected configuration paths should be described in di.xml
  * only send a message if the value was changed
  * the initial command should collect and send all described configuration data
* Consumers(s) on the Message Broker side save the configuration to the corresponding Service via gRPC
  * configuration in di.xml can be used to determine what configuration should be imported to specified service

Proposed service & message structure:
```java
service Catalog { # will be similar for any service 
  rpc importConfig (ImportConfigRequest) returns (ImportConfigResponse)  {}
}

message ImportConfigRequest {
  repeated Config config = 1;
}

message ImportConfigResponse {
  bool status = 1;
  string message = 2;
}

message Config {
  string name = 1;
  string value = 2;
}

```

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/SFAPP-134

**Comment by mslabko** [comment]
E.g. we can have next flow:
```
Admin (Magento)
1. changed system configuration: system/path/searh/price_algo :: auto
2. send message to Message Bus ({name:system/path/searh/price_algo, value:auto}, ...], 
3. in MessageBroker: resolveServiceDestinationAndMapConfigName(messageFromMessageBus)
3.1.  resolved service according to config: "search", config name: "price_algo"
3.2. $service = new SearchGRPCService->ImportConfig([{name: price_algo, value: auto}])

```

**Comment by owlsmage** [comment]
@magento I am working on this

**Comment by owlsmage** [comment]
@magento add to contributors team

**Comment by owlsmage** [comment]
@magento I am working on this

**Comment by owlsmage** [comment]
@mslabko PR for Magento module to export configuration changes https://github.com/magento/commerce-data-export/pull/15
