### ISSUE TITLE
ProductVariants Indexer Fix

### ISSUE THREAD

**Issue by bricht** [magento/catalog-storefront#431]
The product variants indexing process is inefficient, since it depends on catalog_product_category.
Apply changes in https://github.com/magento/commerce-data-export/pull/11 
Fix the faulty plugin so the indexer runs as expected on ee.

1. Removed reliance on generic product index in mview.xml and index.xml
2. Added some queries and plugins to make the indexing more specific and added a workaround for the disfunctional mview, 
    by querying changes manually and adding to ids to the indexer_cl table in a CommitCallback.

**Comment by RuslanKostiv1** [comment]
fixed in scope of https://github.com/magento/catalog-storefront/issues/437
