### ISSUE TITLE
Test Y

### ISSUE THREAD

**Issue by yaroslavGoncharuk** [magento/catalog-storefront#438]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by yaroslavGoncharuk** [comment]
@magento export issue to Jira SFAPP as Story

**Comment by yaroslavGoncharuk** [comment]
@magento export issue to Jira project SFAPP as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-155) is successfully created for this issue.

**Comment by yaroslavGoncharuk** [comment]
@magento I am working on this

**Comment by yaroslavGoncharuk** [comment]
@magento add to contributors team

**Comment by yaroslavGoncharuk** [comment]
@magento I am working on this
