### ISSUE TITLE
WEB-API test failures

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#439]
## Description

The latest PRs were merged with green builds, but new PRs are failing with errors.

<https://github.com/magento-commerce/commerce-data-export/pull/11>

Tests following tests are failing:
* [Magento.CatalogStorefront.Test.Api.ProductVariants.ConfigurableVariantsTest.testConfigurableProductVariants](http://10.234.148.152:8080/job/WebAPI-Tests/7841/testReport/junit/Magento.CatalogStorefront.Test.Api.ProductVariants/ConfigurableVariantsTest/testConfigurableProductVariants_2/)
* [Magento.CatalogStorefront.Test.Api.ProductVariants.ConfigurableVariantsTest.testProductVariantsDisabledProduct](http://10.234.148.152:8080/job/WebAPI-Tests/7841/testReport/junit/Magento.CatalogStorefront.Test.Api.ProductVariants/ConfigurableVariantsTest/testProductVariantsDisabledProduct/)

With the following error:
```java
Magento\CatalogStorefront\Test\Api\ProductVariants\ConfigurableVariantsTest::testProductVariantsDisabledProduct Magento\Framework\Exception\RuntimeException: Storage error: {"error":{"root*cause":<{"type":"index_not_found_exception","reason":"no such index [catalog_storefront_v1__product_variant]","resource.type":"index_or_alias","resource.id":"catalog_storefront_v1__product_variant","index_uuid":"_na_","index":"catalog_storefront_v1__product_variant"}],"type":"index_not_found_exception","reason":"no such index [catalog_storefront_v1__product_variant]","resource.type":"index_or_alias","resource.id":"catalog_storefront_v1__product_variant","index_uuid":"_na_","index":"catalog_storefront_v1__product_variant"},"status":404} Query was:{"index":"catalog_storefront_v1__product_variant","type":"product_variant","body":{"query":{"bool":{"filter":[{"term":{"parent*id":704}}]}}},"size":5000} /var/www/html/app/code/Magento/CatalogStorefront/Model/Storage/Client/ElasticsearchQuery.php:156 /var/www/html/app/code/Magento/CatalogStorefront/Model/Storage/Client/ElasticsearchQuery.php:119 /var/www/html/app/code/Magento/CatalogStorefront/DataProvider/ProductVariantsDataProvider.php:71 /var/www/html/app/code/Magento/CatalogStorefront/Model/VariantService.php:219 /var/www/html/app/code/Magento/CatalogStorefront/Test/Api/ProductVariants/ConfigurableVariantsTest.php:122 /var/www/html/app/code/Magento/CatalogStorefront/Test/Api/StorefrontTestsAbstract.php:184 /var/www/html/app/code/Magento/CatalogStorefront/Test/Api/StorefrontTestsAbstract.php:172
```
## Steps to reproduce

As result of research is was found, that tests don't fail if files links are used instead of copying. The easiest way to reproduce it is to install Magento with DevBox 

[https://github.com/duhon/magento-docker] 

If you install Magento with 

[https://github.com/duhon/magento-docker/blob/80abd84218526c14dd1e97db3f253e1be5863635/.env> 

MUTAGEN_INSTALLATION=YES (links and copying are used)

Tests are green 

MUTAGEN_INSTALLATION=NO (only copying is used)

Mentioned tests are red with the same error. 

**AC**: Builds are green on PR

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/SFAPP-154

**Comment by RuslanKostiv1** [comment]
will be delivered in scope of 
https://github.com/magento/commerce-data-export/pull/2/
https://github.com/magento/catalog-storefront/pull/415
