### ISSUE TITLE
Demo Story 2 update

### ISSUE THREAD

**Issue by yaroslavGoncharuk** [magento/catalog-storefront#441]
### Preconditions (*)

<!---
 Please provide as detailed information about your environment as possible.
 For example Magento version, tag, HEAD, PHP & MySQL version, etc..
 --]
1. # h3. Steps to reproduce (*)
 [!---
 It is important to provide a set of clear steps to reproduce this bug.
 If relevant please include code samples
 --]
1. # # h3. Expected result (*)
 [!--- Tell us what should happen --]
1. [Screenshots, logs or description]

### Actual result (*)

[!--- Tell us what happens instead --]
1. [Screenshots, logs or description>

**Comment by yaroslavGoncharuk** [comment]
@magento export issue to Jira project SFAPP as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-157) is successfully created for this issue.
