### ISSUE TITLE
Use connection pool in MessageBroker

### ISSUE THREAD

**Issue by skovalenk** [magento/catalog-storefront#444]
Add the ability to choose a connection in Message Broker from the connections pool by the given connection name
(see \Magento\CatalogMessageBroker\Model\StorefrontConnector\ConnectionPool::retrieveByConnectionType)

Also, add missed connection name for "catalog" service to all places, where SF API is invoked (example: https://github.com/magento/storefront-message-broker/commit/efce387baa929ab2d705f18c2777676bca395836#diff-b057f653b72b4971f93966196044b97c6b77ff4d9e6e3d77bd17a23582c5cae6R158) :

\Magento\CatalogMessageBroker\Model\MessageBus\ProductVariants\ProductVariantsConsumer::processMessage
\Magento\CatalogMessageBroker\Model\MessageBus\ProductVariants\DeleteProductVariantsConsumer::execute
\Magento\CatalogMessageBroker\Model\MessageBus\Category\DeleteCategoriesConsumer::execute
...

Please, move \Magento\CatalogMessageBroker\Model\StorefrontConnector* to MessageBroker module and add the ability to choose service class according to connection name (right now we have only "catalog" but we will have "product-reviews", "search" and others in future)

**Comment by mslabko** [comment]
@magento export issue to Jira project SFAPP as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-162) is successfully created for this issue.

**Comment by owlsmage** [comment]
@magento I am working on this
