### ISSUE TITLE
Backoffice::Sync prices

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#465]
Add service in Magento Backoffice to retrieve all prices related data for initial sync data

**AC:**
* raw prices of simple products should be returned (without relying on the existing price indexer)
  * special price, special price date
  * tier prices
* custom options prices
* product links prices. (downloadable)
* product/options relations
  * for composite products
  * for custom options

repo: <https://github.com/magento/commerce-data-export]

**Tech details:**
* list of all price-related events https://github.com/magento/catalog-storefront/issues/443#issuecomment-735829704 (only part of them should be honored for synchronization) 
* utilize the same approach (data providers) for raw price collecting data which used in https://github.com/magento/catalog-storefront/issues/443
  * refactor message structure if needed to have similar response for price change event and synchronisation response 
* "id" field in Request/Response object is a string that represents a specific entity, e.g.
  * Introduce Interface to build product id (refactor existing providers, e.g. Magento\CatalogDataExporter\Model\Provider\Product\ProductOptions\OptionValueUid)
  * for product: regular Magento Product ID returned, e.g. "42"
  * for custom option: "option/<custom*option_id]/[custom_option_value*id]"
* use batching for return prices (generators usage is preferred) 
 
```
Proposed response 

{
  "prices":[
    {
      "meta":{
        "code":"price",
        "w":0,
        "cg":1
      },
      "data": [
        {
          "id":"71",
          "value":"12.0"
        },
        // ...
      ]
    },   
    {
      "meta":{
        "code":"tier_price",
        "w":0,
        "cg":1
      },
      "data": [
        {
          "id":"71",
          "value":"12.0",
          "qty": 2
        }
      ]
    }
  >
}

```

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/SFAPP-182

**Comment by bricht** [comment]
@magento I am working on this
