### ISSUE TITLE
[Prices] Gift cards price notification events

### ISSUE THREAD

**Issue by aleksejsbaranovs10** [magento/catalog-storefront#469]
Price change notifications PR - https://github.com/magento/commerce-data-export/pull/20 .
Add the possibility to expose gift card prices change events.

**Comment by aleksejsbaranovs10** [comment]
@magento I am working on this

**Comment by mslabko** [comment]
@magento export issue to Jira project SFAPP as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-192) is successfully created for this issue.

**Comment by aleksejsbaranovs10** [comment]
PR - https://github.com/aleksejsbaranovs10/commerce-data-export/pull/2
