### ISSUE TITLE
Standalone installation of pricing service

### ISSUE THREAD

**Issue by lykhachov** [magento/catalog-storefront#471]
Add the ability to install each Storefront Service as a standalone application 

AC:
* service may depend only on Magento Framework 
* own composer.json configuration to install service 
* CLI command to setup service (resources to DB, connections, etc...)
* global di.xml should have minimum preferences/configuration to handle 
** configure grpc command storefront:grpc:init
** run of gRPC service via ./vendor/bin/grpc-server
** run "setup" service command
* README.md file provide sufficient documentation on how to setup and use service

Repo: https://github.com/magento/storefront-pricing-ce

See an example of init command in storefront-search-ce repo Magento_SearchStorefrontConfig console command

**Comment by mslabko** [comment]
@magento export issue to Jira project SFAPP as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/SFAPP-191) is successfully created for this issue.

**Comment by lykhachov** [comment]
@magento I am working on this
